apiVersion: v1
kind: ReplicationController
metadata:
  name: rc
  labels:
    app: myapp
    type: front-end
spec:
  replicas: 2
  template:
    metadata:
      name: myapp-pod
      labels:
        name: myapp
    spec:
      containers:
      - name: myapp-container
        image: nginx
